name: riverpod_architecture
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  #https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.5.1
  #https://pub.dev/packages/go_router
  go_router: ^14.7.2
  #https://pub.dev/packages/retrofit
  retrofit: ^4.4.2
  #https://pub.dev/packages/dio
  dio: ^5.8.0+1
  #https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.3.0
  #https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4
  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  #https://pub.dev/packages/intl
  intl: ^0.20.2
  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #https://pub.dev/packages/build_runner
  build_runner: ^2.4.14
  #https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^9.1.7
  #https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.3
  #https://pub.dev/packages/freezed
  freezed: ^2.5.8
  #https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
